### ISSUE TITLE
Pre-commit for lychee

### ISSUE THREAD

**Issue by lyndonlim27** [0Upjh80d/agents#20]
**Describe the bug**
Currently the link checker `lychee` that we are using has an open issue where it is unable to be run via pre-commit.

**To Reproduce**

1. Go to '.pre-commit-config.yaml`
2. Add this statement to repos
```yaml
  - repo: https://github.com/lycheeverse/lychee.git
    rev: lychee-v0.18.1
    hooks:
      - id: lychee
        args: ["--no-progress", "."]
        pass_filenames: false
```

3. Run make lint
4. You will get the errror Executable `lychee` not found

**Expected behavior**

It should be able to run `lychee` and check for broken links

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
